[versions]
# Lib
mtproto = "3.0.0-local05"

# Plugins
android-gradle = "8.1.3"
kotlinpoet = "1.14.2"

# Ktor
ktor = "2.3.5"

# Kotlin
kotlin_coroutines = "1.7.3"
kotlin = "1.9.20"

# IO
kotlinx-io = "0.3.0"
nexus-publish = "1.1.0"

# Docs
dokka = "1.9.10"

# Testing
junit = "4.13.2"

[libraries]
# Local (Use as implementation(project(...))
# Usage Example: implementation(project(libs.mtproto.client.api.get().module.name))
mtproto-core = { group = "_", name = ":core" }
mtproto-buffer = { group = "_", name = ":buffer" }
mtproto-serialization = { group = "_", name = ":serialization" }

mtproto-security-cipher = { group = "_", name = ":security:cipher" }
mtproto-security-ige = { group = "_", name = ":security:ige" }
mtproto-security-obfuscation = { group = "_", name = ":security:obfuscation" }
mtproto-security-utils = { group = "_", name = ":security:utils" }
mtproto-security-digest = { group = "_", name = ":security:digest" }

mtproto-client_api = { group = "_", name = ":client:api" }
mtproto-client_sockets_infrastructure = { group = "_", name = ":client:sockets:infrastructure" }

mtproto_generator = { module = "com.attafitamim.mtproto:generator", version.ref = "mtproto" }

# Plugins
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish" }

# WebSockets
ktor_webscokets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor_network = { module = "io.ktor:ktor-network", version.ref = "ktor" }

# Ktor
ktor_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor_logger = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# IO
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }

# Kotlin
kotlin_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin_coroutines" }

[plugins]
java-library = { id = "java-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
maven-publish = { id = "maven-publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
android-gradle-application = { id = "com.android.application", version.ref = "android-gradle" }
android-gradle-library = { id = "com.android.library", version.ref = "android-gradle" }
signing = { id = "signing" }
mtproto-generator = { id = "mtproto-generator" }